from __future__ import annotations

# Golden corpus is generated once into shared/golden/utterances.json
# Keep this as the source of truth for adding cases in code reviews if needed.

ENGLISH = [
    ("Remind me tomorrow at 5 to pick up the car", ["CREATE_REMINDER"]),
    ("Remind me in half an hour to drink water", ["CREATE_REMINDER"]),
    ("Remind me after work to buy shampoo", ["CREATE_REMINDER"]),
    ("Add a task to pay the electricity bill", ["CREATE_TASK"]),
    ("Create a task to send invoices tonight", ["CREATE_TASK"]),
    ("Mark the grocery task as done", ["COMPLETE_TASK"]),
    ("Put a meeting with Maya Thursday at 2", ["CREATE_CALENDAR_EVENT"]),
    ("Add a session with Joe tomorrow at 3pm", ["CREATE_CALENDAR_EVENT"]),
    ("Move my meeting with Karim to Thursday", ["UPDATE_CALENDAR_EVENT"]),
    ("Reschedule the meeting with Maya to 4pm", ["UPDATE_CALENDAR_EVENT"]),
    ("Cancel the meeting with Karim", ["DELETE_CALENDAR_EVENT"]),
    ("Delete tomorrow's event with Maya", ["DELETE_CALENDAR_EVENT"]),
    ("What's on my calendar tomorrow?", ["QUERY_CALENDAR"]),
    ("What is on my schedule today?", ["QUERY_CALENDAR"]),
    ("Draft an email to Karim that the report is done", ["DRAFT_EMAIL"]),
    ("Tomorrow email Karim that the report is done", ["SEND_EMAIL"]),
    ("Send an email to Sara I'm running late", ["SEND_EMAIL"]),
    ("Search email for invoice from last week", ["SEARCH_EMAIL"]),
    ("Call Maya", ["CALL_CONTACT"]),
    ("Call my boss", ["CALL_CONTACT"]),
    ("Text Nour that I'm downstairs", ["PREPARE_SMS"]),
    ("Send Nour a WhatsApp asking if she wants a session at 3", ["PREPARE_WHATSAPP"]),
    ("Ask Nour if she wants a session at 3", ["PREPARE_WHATSAPP"]),
    ("Send this on Telegram to Karim", ["PREPARE_TELEGRAM"]),
    ("Send the last photo to Maya", ["SHARE_MEDIA"]),
    ("Save a note that the lockbox code changed", ["SAVE_NOTE"]),
    ("What am I forgetting this week?", ["QUERY_TASKS"]),
    ("What tasks do I still have?", ["QUERY_TASKS"]),
    ("Who is mama in my memory?", ["QUERY_MEMORY"]),
    ("Tomorrow email Karim that the report is done and put a meeting with Maya Thursday at 2", ["SEND_EMAIL", "CREATE_CALENDAR_EVENT"]),
]

ARABIC = [
    ("ذكرني بكرا عالخمسة جيب السيارة", ["CREATE_REMINDER"]),
    ("ذكرني بعد شوي أشرب مي", ["CREATE_REMINDER"]),
    ("ذكرني بعد الشغل جيب شامبو", ["CREATE_REMINDER"]),
    ("ضيف مهمة دفع الكهرباء", ["CREATE_TASK"]),
    ("مهمة: ابعت الفواتير", ["CREATE_TASK"]),
    ("خلصت مهمة البقالة", ["COMPLETE_TASK"]),
    ("حط جلسة مع مايا الخميس الساعة 2", ["CREATE_CALENDAR_EVENT"]),
    ("ضيف موعد مع جو بكرا الساعة 3", ["CREATE_CALENDAR_EVENT"]),
    ("غير الموعد مع كريم على الخميس", ["UPDATE_CALENDAR_EVENT"]),
    ("أجل الاجتماع مع مايا للساعة 4", ["UPDATE_CALENDAR_EVENT"]),
    ("الغي الاجتماع مع كريم", ["DELETE_CALENDAR_EVENT"]),
    ("امسح حدث بكرا مع مايا", ["DELETE_CALENDAR_EVENT"]),
    ("شو عندي بكرا؟", ["QUERY_CALENDAR"]),
    ("شو عندي اليوم؟", ["QUERY_CALENDAR"]),
    ("اكتب ايميل لكريم إن التقرير جاهز", ["DRAFT_EMAIL"]),
    ("ابعت ايميل لكريم إن التقرير خلص", ["SEND_EMAIL"]),
    ("ابعت ايميل لسارة إني رح إتأخر", ["SEND_EMAIL"]),
    ("دور عالايميل على الفاتورة", ["SEARCH_EMAIL"]),
    ("دق لمايا", ["CALL_CONTACT"]),
    ("دق للمعلم", ["CALL_CONTACT"]),
    ("ابعت رسالة نصية لنور إني تحت", ["PREPARE_SMS"]),
    ("اسأل نور إذا بدها جلسة الساعة 3", ["PREPARE_WHATSAPP"]),
    ("ابعت لواتساب لنور إذا بدها جلسة", ["PREPARE_WHATSAPP"]),
    ("ابعت لتلغرام لكريم", ["PREPARE_TELEGRAM"]),
    ("ابعت الصورة لمايا", ["SHARE_MEDIA"]),
    ("سجل إنو رمز الصندوق تغير", ["SAVE_NOTE"]),
    ("شو نسيت هالأسبوع؟", ["QUERY_TASKS"]),
    ("شو المهام الباقية؟", ["QUERY_TASKS"]),
    ("مين ماما بالذاكرة؟", ["QUERY_MEMORY"]),
    ("بكرا ابعت ايميل لكريم إن التقرير جاهز وحط اجتماع مع مايا الخميس الساعة 2", ["SEND_EMAIL", "CREATE_CALENDAR_EVENT"]),
]

ARABIZI = [
    ("zakirne bokra 3al 5 jib l siyara mn 3end l mecanicien", ["CREATE_REMINDER"]),
    ("zakirne ba3d shway shrab may", ["CREATE_REMINDER"]),
    ("zakerni ba3d l shoghl jib shampoo", ["CREATE_REMINDER"]),
    ("zakirne today 3al 7 call the mechanic", ["CREATE_REMINDER"]),
    ("remind me bokra soboh jib l khebz", ["CREATE_REMINDER"]),
    ("zakirne masa 3al 8 study", ["CREATE_REMINDER"]),
    ("add task dfa3 l kahraba", ["CREATE_TASK"]),
    ("task: eb3at l invoices", ["CREATE_TASK"]),
    ("complete task groceries", ["COMPLETE_TASK"]),
    ("put meeting with Maya thursday at 2", ["CREATE_CALENDAR_EVENT"]),
    ("bokra 3ande meeting at 3, remind me abla bi nos se3a", ["CREATE_CALENDAR_EVENT", "CREATE_REMINDER"]),
    ("session with Maya bokra 3al 3", ["CREATE_CALENDAR_EVENT"]),
    ("move meeting with Karim to thursday", ["UPDATE_CALENDAR_EVENT"]),
    ("reschedule meeting Maya to 4pm", ["UPDATE_CALENDAR_EVENT"]),
    ("cancel meeting with Karim", ["DELETE_CALENDAR_EVENT"]),
    ("shu 3ande bokra?", ["QUERY_CALENDAR"]),
    ("shu 3andi today?", ["QUERY_CALENDAR"]),
    ("eb3at email la Karim enne ra7 et2akhar", ["SEND_EMAIL"]),
    ("Tomorrow email Karim that the report is done", ["SEND_EMAIL"]),
    ("draft email la Sara the report is ready", ["DRAFT_EMAIL"]),
    ("ابعت email لـ Karim وقله the report is ready", ["SEND_EMAIL"]),
    ("search email invoice", ["SEARCH_EMAIL"]),
    ("de2 Maya", ["CALL_CONTACT"]),
    ("call mama", ["CALL_CONTACT"]),
    ("de2 my boss", ["CALL_CONTACT"]),
    ("eb3at sms la Nour enne tahet", ["PREPARE_SMS"]),
    ("Ask Nour if she wants a session at 3", ["PREPARE_WHATSAPP"]),
    ("Bokra 3al 3 ask Maya if she wants a session", ["PREPARE_WHATSAPP"]),
    ("eb3at la Maya 3al whatsapp if she wants a session", ["PREPARE_WHATSAPP"]),
    ("ba3d l meeting send Maya a message", ["PREPARE_WHATSAPP"]),
    ("send telegram la Karim", ["PREPARE_TELEGRAM"]),
    ("send last photo to Maya", ["SHARE_MEDIA"]),
    ("save note lockbox code changed", ["SAVE_NOTE"]),
    ("what am i forgetting", ["QUERY_TASKS"]),
    ("shu neseet", ["CREATE_TASK"]),
    ("who is mama", ["QUERY_MEMORY"]),
    ("zakirne bokra 3al 5 and email Karim I'm late", ["CREATE_REMINDER", "SEND_EMAIL"]),
    ("ask Nour if she wants a session and put it on my calendar thursday at 2", ["PREPARE_WHATSAPP", "CREATE_CALENDAR_EVENT"]),
    ("eb3at la Karim enne ra7 et2akhar and zakirne ba3d shway", ["PREPARE_WHATSAPP", "CREATE_REMINDER"]),
    ("shu 3ande bokra and remind me to buy shampoo after work", ["QUERY_CALENDAR", "CREATE_REMINDER"]),
    ("call Maya and ask Nour if she wants a session at 3", ["CALL_CONTACT", "PREPARE_WHATSAPP"]),
    ("create task buy milk and remind me bokra 3al 9", ["CREATE_TASK", "CREATE_REMINDER"]),
    ("put meeting with Karim tomorrow at 10am", ["CREATE_CALENDAR_EVENT"]),
    ("delete event with Maya", ["DELETE_CALENDAR_EVENT"]),
    ("move my meeting with Karim tomorrow from 2 to 3", ["UPDATE_CALENDAR_EVENT"]),
    ("email George tomorrow at 9", ["SEND_EMAIL"]),
    ("zakirne jib l siyara", ["CREATE_REMINDER"]),
    ("hala2 remind me in half an hour", ["CREATE_REMINDER"]),
    ("send photo to Nour", ["SHARE_MEDIA"]),
    ("telegram Karim I'm downstairs", ["PREPARE_TELEGRAM"]),
    ("sms Nour I'm late", ["PREPARE_SMS"]),
    ("draft email to my boss I'm sick", ["DRAFT_EMAIL"]),
    ("what's on my calendar bokra", ["QUERY_CALENDAR"]),
    ("complete task study", ["COMPLETE_TASK"]),
    ("save note Maya prefers whatsapp", ["SAVE_NOTE"]),
]


def all_cases() -> list[dict]:
    rows = []
    for idx, (text, types) in enumerate(ENGLISH, start=1):
        rows.append({"id": f"en-{idx:02d}", "lang": "en", "text": text, "expected_types": types})
    for idx, (text, types) in enumerate(ARABIC, start=1):
        rows.append({"id": f"ar-{idx:02d}", "lang": "ar", "text": text, "expected_types": types})
    for idx, (text, types) in enumerate(ARABIZI, start=1):
        rows.append({"id": f"az-{idx:02d}", "lang": "arabizi", "text": text, "expected_types": types})
    return rows
